from flask import Flask, render_template, request, redirect, url_for

app = Flask(__name__)

# Datos simulados en memoria
games = [
    {'id': 1, 'name': 'The Legend of Zelda: Breath of the Wild', 'genre': 'Adventure'},
    {'id': 2, 'name': 'Super Mario Odyssey', 'genre': 'Platform'},
    {'id': 3, 'name': 'Red Dead Redemption 2', 'genre': 'Action-Adventure'},
    {'id': 4, 'name': 'The Witcher 3: Wild Hunt', 'genre': 'RPG'},
    {'id': 5, 'name': 'God of War', 'genre': 'Action-Adventure'},
    {'id': 6, 'name': 'Horizon Zero Dawn', 'genre': 'Action-RPG'},
    {'id': 7, 'name': 'Spider-Man', 'genre': 'Action-Adventure'},
    {'id': 8, 'name': 'Minecraft', 'genre': 'Sandbox'},
    {'id': 9, 'name': 'Fortnite', 'genre': 'Battle Royale'},
    {'id': 10, 'name': 'Among Us', 'genre': 'Party'},
    {'id': 11, 'name': 'Cyberpunk 2077', 'genre': 'RPG'},
    {'id': 12, 'name': 'Animal Crossing: New Horizons', 'genre': 'Simulation'},
    {'id': 13, 'name': 'Dark Souls III', 'genre': 'Action RPG'},
    {'id': 14, 'name': 'Sekiro: Shadows Die Twice', 'genre': 'Action-Adventure'},
    {'id': 15, 'name': 'Final Fantasy VII Remake', 'genre': 'RPG'},
    {'id': 16, 'name': 'Ghost of Tsushima', 'genre': 'Action-Adventure'},
    {'id': 17, 'name': 'Resident Evil 2', 'genre': 'Survival Horror'},
    {'id': 18, 'name': 'The Elder Scrolls V: Skyrim', 'genre': 'RPG'},
    {'id': 19, 'name': 'Assassin’s Creed Valhalla', 'genre': 'Action-RPG'},
    {'id': 20, 'name': 'Doom Eternal', 'genre': 'First-person shooter'},
    {'id': 21, 'name': 'The Last of Us Part II', 'genre': 'Action-Adventure'},
    {'id': 22, 'name': 'Uncharted 4: A Thief’s End', 'genre': 'Action-Adventure'},
    {'id': 23, 'name': 'Bloodborne', 'genre': 'Action RPG'},
    {'id': 24, 'name': 'Control', 'genre': 'Action-Adventure'},
    {'id': 25, 'name': 'Apex Legends', 'genre': 'Battle Royale'},
    {'id': 26, 'name': 'The Sims 4', 'genre': 'Simulation'},
    {'id': 27, 'name': 'Overwatch', 'genre': 'First-person shooter'},
    {'id': 28, 'name': 'Destiny 2', 'genre': 'Action RPG'},
    {'id': 29, 'name': 'FIFA 21', 'genre': 'Sports'},
    {'id': 30, 'name': 'NBA 2K21', 'genre': 'Sports'},
    {'id': 31, 'name': 'Rocket League', 'genre': 'Sports'},
    {'id': 32, 'name': 'Stardew Valley', 'genre': 'Simulation'},
    {'id': 33, 'name': 'Terraria', 'genre': 'Sandbox'},
    {'id': 34, 'name': 'Genshin Impact', 'genre': 'Action RPG'},
    {'id': 35, 'name': 'Hades', 'genre': 'Roguelike'},
    {'id': 36, 'name': 'Fall Guys: Ultimate Knockout', 'genre': 'Party'},
    {'id': 37, 'name': 'Valorant', 'genre': 'First-person shooter'},
    {'id': 38, 'name': 'Half-Life: Alyx', 'genre': 'First-person shooter'},
    {'id': 39, 'name': 'Outer Wilds', 'genre': 'Adventure'},
    {'id': 40, 'name': 'Death Stranding', 'genre': 'Action-Adventure'},
    {'id': 41, 'name': 'Halo Infinite', 'genre': 'First-person shooter'},
    {'id': 42, 'name': 'Monster Hunter: World', 'genre': 'Action RPG'},
    {'id': 43, 'name': 'Nioh 2', 'genre': 'Action RPG'},
    {'id': 44, 'name': 'Cuphead', 'genre': 'Platformer'},
    {'id': 45, 'name': 'Celeste', 'genre': 'Platformer'},
    {'id': 46, 'name': 'Dead Cells', 'genre': 'Roguelike'},
    {'id': 47, 'name': 'Hollow Knight', 'genre': 'Metroidvania'},
    {'id': 48, 'name': 'Slay the Spire', 'genre': 'Roguelike'},
    {'id': 49, 'name': 'Divinity: Original Sin 2', 'genre': 'RPG'},
    {'id': 50, 'name': 'Persona 5', 'genre': 'RPG'},
    {'id': 51, 'name': 'Metal Gear Solid V: The Phantom Pain', 'genre': 'Action-Adventure'},
    {'id': 52, 'name': 'XCOM 2', 'genre': 'Strategy'},
    {'id': 53, 'name': 'The Outer Worlds', 'genre': 'RPG'},
    {'id': 54, 'name': 'Prey', 'genre': 'First-person shooter'},
    {'id': 55, 'name': 'Dishonored 2', 'genre': 'Action-Adventure'},
    {'id': 56, 'name': 'Dishonored', 'genre': 'Action-Adventure'},
    {'id': 57, 'name': 'BioShock Infinite', 'genre': 'First-person shooter'},
    {'id': 58, 'name': 'Mass Effect 2', 'genre': 'RPG'},
    {'id': 59, 'name': 'Mass Effect 3', 'genre': 'RPG'},
    {'id': 60, 'name': 'Star Wars Jedi: Fallen Order', 'genre': 'Action-Adventure'},
    {'id': 61, 'name': 'Sekiro: Shadows Die Twice', 'genre': 'Action-Adventure'},
    {'id': 62, 'name': 'Bloodborne', 'genre': 'Action RPG'},
    {'id': 63, 'name': 'Dark Souls III', 'genre': 'Action RPG'},
    {'id': 64, 'name': 'The Legend of Zelda: Breath of the Wild', 'genre': 'Adventure'},
    {'id': 65, 'name': 'Super Mario Odyssey', 'genre': 'Platformer'},
    {'id': 66, 'name': 'Hollow Knight', 'genre': 'Metroidvania'},
    {'id': 67, 'name': 'Celeste', 'genre': 'Platformer'},
    {'id': 68, 'name': 'The Witcher 3: Wild Hunt', 'genre': 'RPG'},
    {'id': 69, 'name': 'Hades', 'genre': 'Roguelike'},
    {'id': 70, 'name': 'Doom Eternal', 'genre': 'First-person shooter'},
    {'id': 71, 'name': 'Half-Life: Alyx', 'genre': 'First-person shooter'},
    {'id': 72, 'name': 'Red Dead Redemption 2', 'genre': 'Action-Adventure'},
    {'id': 73, 'name': 'Resident Evil 2', 'genre': 'Survival Horror'},
    {'id': 74, 'name': 'Control', 'genre': 'Action-Adventure'},
    {'id': 75, 'name': 'Cyberpunk 2077', 'genre': 'RPG'},
    {'id': 76, 'name': 'Ghost of Tsushima', 'genre': 'Action-Adventure'},
    {'id': 77, 'name': 'Marvel’s Spider-Man', 'genre': 'Action-Adventure'},
    {'id': 78, 'name': 'God of War', 'genre': 'Action-Adventure'},
    {'id': 79, 'name': 'Final Fantasy VII Remake', 'genre': 'RPG'},
    {'id': 80, 'name': 'Death Stranding', 'genre': 'Action-Adventure'},
    {'id': 81, 'name': 'The Outer Worlds', 'genre': 'RPG'},
{'id': 82, 'name': 'Subnautica', 'genre': 'Survival'},
{'id': 83, 'name': 'Horizon Forbidden West', 'genre': 'Action-RPG'},
{'id': 84, 'name': 'Metroid Dread', 'genre': 'Action-Adventure'},
{'id': 85, 'name': 'Bayonetta 2', 'genre': 'Action'},
{'id': 86, 'name': 'Splatoon 2', 'genre': 'Shooter'},
{'id': 87, 'name': 'Luigi\'s Mansion 3', 'genre': 'Adventure'},
{'id': 88, 'name': 'Fire Emblem: Three Houses', 'genre': 'Strategy'},
{'id': 89, 'name': 'Xenoblade Chronicles 2', 'genre': 'RPG'},
{'id': 90, 'name': 'Octopath Traveler', 'genre': 'RPG'},
{'id': 91, 'name': 'Ring Fit Adventure', 'genre': 'Fitness'},
{'id': 92, 'name': 'Paper Mario: The Origami King', 'genre': 'RPG'},
{'id': 93, 'name': 'Astral Chain', 'genre': 'Action'},
{'id': 94, 'name': 'Bravely Default II', 'genre': 'RPG'},
{'id': 95, 'name': 'Triangle Strategy', 'genre': 'Strategy'},
{'id': 96, 'name': 'Dragon Quest XI', 'genre': 'RPG'},
{'id': 97, 'name': 'Monster Hunter Rise', 'genre': 'Action RPG'},
{'id': 98, 'name': 'Mario Kart 8 Deluxe', 'genre': 'Racing'},
{'id': 99, 'name': 'Super Smash Bros. Ultimate', 'genre': 'Fighting'},
{'id': 100, 'name': 'Pikmin 3 Deluxe', 'genre': 'Strategy'},
{'id': 101, 'name': 'Kirby Star Allies', 'genre': 'Platformer'},
{'id': 102, 'name': 'Yoshi\'s Crafted World', 'genre': 'Platformer'},
{'id': 103, 'name': 'Captain Toad: Treasure Tracker', 'genre': 'Puzzle'},
{'id': 104, 'name': 'Donkey Kong Country: Tropical Freeze', 'genre': 'Platformer'},
{'id': 105, 'name': 'Shovel Knight', 'genre': 'Platformer'},
{'id': 106, 'name': 'Ori and the Blind Forest', 'genre': 'Metroidvania'},
{'id': 107, 'name': 'Ori and the Will of the Wisps', 'genre': 'Metroidvania'},
{'id': 108, 'name': 'Spiritfarer', 'genre': 'Simulation'},
{'id': 109, 'name': 'Untitled Goose Game', 'genre': 'Puzzle'},
{'id': 110, 'name': 'Little Nightmares II', 'genre': 'Horror'},
{'id': 111, 'name': 'Cuphead', 'genre': 'Platformer'},
{'id': 112, 'name': 'Celeste', 'genre': 'Platformer'},
{'id': 113, 'name': 'Dead Cells', 'genre': 'Roguelike'},
{'id': 114, 'name': 'Hollow Knight', 'genre': 'Metroidvania'},
{'id': 115, 'name': 'Slay the Spire', 'genre': 'Roguelike'},
{'id': 116, 'name': 'Divinity: Original Sin 2', 'genre': 'RPG'},
{'id': 117, 'name': 'Persona 5', 'genre': 'RPG'},
{'id': 118, 'name': 'Metal Gear Solid V: The Phantom Pain', 'genre': 'Action-Adventure'},
{'id': 119, 'name': 'XCOM 2', 'genre': 'Strategy'},
{'id': 120, 'name': 'The Outer Worlds', 'genre': 'RPG'},
{'id': 121, 'name': 'Prey', 'genre': 'First-person shooter'},
{'id': 122, 'name': 'Dishonored 2', 'genre': 'Action-Adventure'},
{'id': 123, 'name': 'BioShock Infinite', 'genre': 'First-person shooter'},
{'id': 124, 'name': 'Mass Effect 2', 'genre': 'RPG'},
{'id': 125, 'name': 'Mass Effect 3', 'genre': 'RPG'},
{'id': 126, 'name': 'Star Wars Jedi: Fallen Order', 'genre': 'Action-Adventure'},
{'id': 127, 'name': 'The Last of Us Remastered', 'genre': 'Action-Adventure'},
{'id': 128, 'name': 'Shadow of the Colossus', 'genre': 'Action-Adventure'},
{'id': 129, 'name': 'Horizon Zero Dawn', 'genre': 'Action-RPG'},
{'id': 130, 'name': 'Bloodborne', 'genre': 'Action RPG'},
{'id': 131, 'name': 'Animal Crossing: New Horizons', 'genre': 'Life Simulation'},
{'id': 132, 'name': 'Sonic Mania', 'genre': 'Platformer'},
{'id': 133, 'name': 'Super Mario Odyssey', 'genre': 'Platformer'},
{'id': 134, 'name': 'Animal Crossing: New Leaf', 'genre': 'Life Simulation'},
{'id': 135, 'name': 'Sonic Generations', 'genre': 'Platformer'},
{'id': 136, 'name': 'Super Mario 3D World', 'genre': 'Platformer'},
{'id': 137, 'name': 'Animal Crossing: Wild World', 'genre': 'Life Simulation'},
{'id': 138, 'name': 'Sonic Adventure 2', 'genre': 'Platformer'},
{'id': 139, 'name': 'Super Mario Galaxy', 'genre': 'Platformer'},
{'id': 140, 'name': 'Animal Crossing', 'genre': 'Life Simulation'},
{'id': 141, 'name': 'Sonic Adventure', 'genre': 'Platformer'},
{'id': 142, 'name': 'Super Mario Sunshine', 'genre': 'Platformer'},
{'id': 143, 'name': 'The Legend of Zelda: Ocarina of Time', 'genre': 'Action-Adventure'},
{'id': 144, 'name': 'Pokémon Red/Blue', 'genre': 'RPG'},
{'id': 145, 'name': 'Tetris', 'genre': 'Puzzle'},
{'id': 146, 'name': 'Grand Theft Auto V', 'genre': 'Action-Adventure'},
{'id': 147, 'name': 'Minecraft', 'genre': 'Sandbox'},
{'id': 148, 'name': 'The Elder Scrolls V: Skyrim', 'genre': 'RPG'},
{'id': 149, 'name': 'Super Mario Bros.', 'genre': 'Platformer'},
{'id': 150, 'name': 'The Legend of Zelda: A Link to the Past', 'genre': 'Action-Adventure'},
{'id': 151, 'name': 'Final Fantasy VII', 'genre': 'RPG'},
{'id': 152, 'name': 'Street Fighter II', 'genre': 'Fighting'},
{'id': 153, 'name': 'Super Mario 64', 'genre': 'Platformer'},
{'id': 154, 'name': 'Pac-Man', 'genre': 'Arcade'},
{'id': 155, 'name': 'The Witcher 3: Wild Hunt', 'genre': 'RPG'},
{'id': 156, 'name': 'Dark Souls', 'genre': 'Action RPG'},
{'id': 157, 'name': 'GTA: San Andreas', 'genre': 'Action-Adventure'},
{'id': 158, 'name': 'Portal', 'genre': 'Puzzle'},
{'id': 159, 'name': 'Red Dead Redemption 2', 'genre': 'Action-Adventure'},
{'id': 160, 'name': 'Half-Life 2', 'genre': 'First-person shooter'},
{'id': 161, 'name': 'Metal Gear Solid', 'genre': 'Stealth'},
{'id': 162, 'name': 'Final Fantasy VI', 'genre': 'RPG'},
{'id': 163, 'name': 'Minecraft: Java Edition', 'genre': 'Sandbox'},
{'id': 164, 'name': 'Minecraft: Bedrock Edition', 'genre': 'Sandbox'},
{'id': 165, 'name': 'God of War (2005)', 'genre': 'Action-Adventure'},
{'id': 166, 'name': 'God of War II', 'genre': 'Action-Adventure'},
{'id': 167, 'name': 'God of War: Chains of Olympus', 'genre': 'Action-Adventure'},
{'id': 168, 'name': 'God of War: Ghost of Sparta', 'genre': 'Action-Adventure'},
{'id': 169, 'name': 'God of War III', 'genre': 'Action-Adventure'},
{'id': 170, 'name': 'God of War: Ascension', 'genre': 'Action-Adventure'},
{'id': 171, 'name': 'God of War (2018)', 'genre': 'Action-Adventure'},
{'id': 172, 'name': 'Crash Bandicoot', 'genre': 'Platformer'},
{'id': 173, 'name': 'Crash Bandicoot 2: Cortex Strikes Back', 'genre': 'Platformer'},
{'id': 174, 'name': 'Crash Bandicoot: Warped', 'genre': 'Platformer'},
{'id': 175, 'name': 'Crash Team Racing', 'genre': 'Racing'},
{'id': 176, 'name': 'Crash Bash', 'genre': 'Party'},
{'id': 177, 'name': 'Crash Bandicoot: The Wrath of Cortex', 'genre': 'Platformer'},
{'id': 178, 'name': 'Crash Bandicoot: The Huge Adventure', 'genre': 'Platformer'},
{'id': 179, 'name': 'Crash Bandicoot 2: N-Tranced', 'genre': 'Platformer'},
{'id': 180, 'name': 'Crash Nitro Kart', 'genre': 'Racing'},
{'id': 181, 'name': 'Crash Bandicoot Purple: Ripto\'s Rampage', 'genre': 'Platformer'},
{'id': 182, 'name': 'Crash Twinsanity', 'genre': 'Platformer'},
{'id': 183, 'name': 'Crash Tag Team Racing', 'genre': 'Racing'},
{'id': 184, 'name': 'Crash Boom Bang!', 'genre': 'Party'},
{'id': 185, 'name': 'Crash of the Titans', 'genre': 'Platformer'},
{'id': 186, 'name': 'Crash: Mind over Mutant', 'genre': 'Platformer'},
{'id': 187, 'name': 'Crash Bandicoot N. Sane Trilogy', 'genre': 'Platformer'},
{'id': 188, 'name': 'Crash Team Racing Nitro-Fueled', 'genre': 'Racing'},
{'id': 189, 'name': 'Lego Island', 'genre': 'Action-Adventure'},
{'id': 190, 'name': 'Lego Racers', 'genre': 'Racing'},
{'id': 191, 'name': 'Lego Rock Raiders', 'genre': 'Real-Time Strategy'},
{'id': 192, 'name': 'Lego Creator', 'genre': 'Simulation'},
{'id': 193, 'name': 'Lego Chess', 'genre': 'Chess'},
{'id': 194, 'name': 'Lego Alpha Team', 'genre': 'Action'},
{'id': 195, 'name': 'Lego Stunt Rally', 'genre': 'Racing'},
{'id': 196, 'name': 'Lego Loco', 'genre': 'Construction and management simulation'},
{'id': 197, 'name': 'Island Xtreme Stunts', 'genre': 'Action-Adventure'},
{'id': 198, 'name': 'Lego Creator: Knights\' Kingdom', 'genre': 'Construction and management simulation'},
{'id': 199, 'name': 'Lego Island 2: The Brickster\'s Revenge', 'genre': 'Action-Adventure'},
{'id': 200, 'name': 'Lego Bionicle', 'genre': 'Action-Adventure'},
{'id': 201, 'name': 'Lego Racers 2', 'genre': 'Racing'},
{'id': 202, 'name': 'Bionicle: The Game', 'genre': 'Action-Adventure'},
{'id': 203, 'name': 'Lego Creator: Harry Potter', 'genre': 'Construction and management simulation'},
{'id': 204, 'name': 'Lego Island Xtreme Stunts', 'genre': 'Action-Adventure'},
{'id': 205, 'name': 'Lego Star Wars: The Video Game', 'genre': 'Action-Adventure'},
{'id': 206, 'name': 'Lego Knights\' Kingdom', 'genre': 'Action-Adventure'},
{'id': 207, 'name': 'Lego Chess', 'genre': 'Chess'},
{'id': 208, 'name': 'Lego Drome Racers', 'genre': 'Racing'},
{'id': 209, 'name': 'Lego Creator: Harry Potter and the Chamber of Secrets', 'genre': 'Construction and management simulation'},
{'id': 210, 'name': 'Lego Creator: Knights\' Kingdom', 'genre': 'Construction and management simulation'},
{'id': 211, 'name': 'Lego Basketball', 'genre': 'Sports'},
{'id': 212, 'name': 'Bionicle Heroes', 'genre': 'Action-Adventure'},
{'id': 213, 'name': 'Lego Star Wars II: The Original Trilogy', 'genre': 'Action-Adventure'},
{'id': 214, 'name': 'Lego Star Wars: The Complete Saga', 'genre': 'Action-Adventure'},
{'id': 215, 'name': 'Lego Indiana Jones: The Original Adventures', 'genre': 'Action-Adventure'},
{'id': 216, 'name': 'Lego Batman: The Videogame', 'genre': 'Action-Adventure'},
{'id': 217, 'name': 'Lego Indiana Jones 2: The Adventure Continues', 'genre': 'Action-Adventure'},
{'id': 218, 'name': 'Lego Rock Band', 'genre': 'Rhythm game'},
{'id': 219, 'name': 'Lego Harry Potter: Years 1–4', 'genre': 'Action-Adventure'},
{'id': 220, 'name': 'Lego Universe', 'genre': 'Massively multiplayer online game'},
{'id': 221, 'name': 'Lego Battles: Ninjago', 'genre': 'Real-Time Strategy'},
{'id': 222, 'name': 'Lego Pirates of the Caribbean: The Video Game', 'genre': 'Action-Adventure'},
{'id': 223, 'name': 'Lego Harry Potter: Years 5–7', 'genre': 'Action-Adventure'},
{'id': 224, 'name': 'Lego City Undercover', 'genre': 'Action-Adventure'},
{'id': 225, 'name': 'Lego City Undercover: The Chase Begins', 'genre': 'Action-Adventure'},
{'id': 226, 'name': 'Lego Legends of Chima Online', 'genre': 'Massively multiplayer online game'},
{'id': 227, 'name': 'Lego Marvel Super Heroes', 'genre': 'Action-Adventure'},
{'id': 228, 'name': 'Lego Friends', 'genre': 'Simulation'},
{'id': 229, 'name': 'Lego Marvel Super Heroes: Universe in Peril', 'genre': 'Action-Adventure'},
{'id': 230, 'name': 'Lego The Hobbit', 'genre': 'Action-Adventure'},
{'id': 231, 'name': 'Lego The Lord of the Rings', 'genre': 'Action-Adventure'},
{'id': 232, 'name': 'Lego City Undercover', 'genre': 'Action-Adventure'},
{'id': 233, 'name': 'Lego Marvel Super Heroes 2', 'genre': 'Action-Adventure'},
{'id': 234, 'name': 'Lego The Incredibles', 'genre': 'Action-Adventure'},
{'id': 235, 'name': 'Lego DC Super-Villains', 'genre': 'Action-Adventure'},
{'id': 236, 'name': 'Castlevania', 'genre': 'Action-Adventure'},
{'id': 237, 'name': 'Castlevania II: Simon\'s Quest', 'genre': 'Action-Adventure'},
{'id': 238, 'name': 'Castlevania III: Dracula\'s Curse', 'genre': 'Action-Adventure'},
{'id': 239, 'name': 'Super Castlevania IV', 'genre': 'Action-Adventure'},
{'id': 240, 'name': 'Castlevania: Symphony of the Night', 'genre': 'Action-Adventure'},
{'id': 241, 'name': 'Castlevania: Aria of Sorrow', 'genre': 'Action-Adventure'},
{'id': 242, 'name': 'Castlevania: Dawn of Sorrow', 'genre': 'Action-Adventure'},
{'id': 243, 'name': 'Castlevania: Portrait of Ruin', 'genre': 'Action-Adventure'},
{'id': 244, 'name': 'Castlevania: Order of Ecclesia', 'genre': 'Action-Adventure'},
{'id': 245, 'name': 'Need for Speed', 'genre': 'Racing'},
{'id': 246, 'name': 'Need for Speed II', 'genre': 'Racing'},
{'id': 247, 'name': 'Need for Speed III: Hot Pursuit', 'genre': 'Racing'},
{'id': 248, 'name': 'Need for Speed: Underground', 'genre': 'Racing'},
{'id': 249, 'name': 'Need for Speed: Most Wanted', 'genre': 'Racing'},
{'id': 250, 'name': 'Need for Speed: Carbon', 'genre': 'Racing'},
{'id': 251, 'name': 'Metroid', 'genre': 'Action-Adventure'},
{'id': 252, 'name': 'Metroid II: Return of Samus', 'genre': 'Action-Adventure'},
{'id': 253, 'name': 'Super Metroid', 'genre': 'Action-Adventure'},
{'id': 254, 'name': 'Metroid Fusion', 'genre': 'Action-Adventure'},
{'id': 255, 'name': 'Metroid: Zero Mission', 'genre': 'Action-Adventure'},
{'id': 256, 'name': 'Mortal Kombat', 'genre': 'Fighting'},
{'id': 257, 'name': 'Mortal Kombat II', 'genre': 'Fighting'},
{'id': 258, 'name': 'Mortal Kombat 3', 'genre': 'Fighting'},
{'id': 259, 'name': 'Mortal Kombat 4', 'genre': 'Fighting'},
{'id': 260, 'name': 'Mortal Kombat: Deadly Alliance', 'genre': 'Fighting'},
{'id': 261, 'name': 'Mortal Kombat: Deception', 'genre': 'Fighting'},
{'id': 262, 'name': 'Mortal Kombat: Armageddon', 'genre': 'Fighting'},
{'id': 263, 'name': 'Mortal Kombat vs. DC Universe', 'genre': 'Fighting'},
{'id': 264, 'name': 'Mortal Kombat (2011)', 'genre': 'Fighting'},
{'id': 265, 'name': 'Mortal Kombat X', 'genre': 'Fighting'},
{'id': 266, 'name': 'Mortal Kombat 11', 'genre': 'Fighting'},
{'id': 267, 'name': 'Dragon Quest', 'genre': 'RPG'},
{'id': 268, 'name': 'Dragon Quest II', 'genre': 'RPG'},
{'id': 269, 'name': 'Dragon Quest III', 'genre': 'RPG'},
{'id': 270, 'name': 'Dragon Quest IV', 'genre': 'RPG'},
{'id': 271, 'name': 'Dragon Quest V', 'genre': 'RPG'},
{'id': 272, 'name': 'Dragon Quest VI', 'genre': 'RPG'},
{'id': 273, 'name': 'Dragon Quest VII', 'genre': 'RPG'},
{'id': 274, 'name': 'Dragon Quest VIII', 'genre': 'RPG'},
{'id': 275, 'name': 'Dragon Quest IX', 'genre': 'RPG'},
{'id': 276, 'name': 'Dragon Quest X', 'genre': 'RPG'},
{'id': 277, 'name': 'Dragon Quest XI', 'genre': 'RPG'},
{'id': 278, 'name': 'Gears of War', 'genre': 'Third-person shooter'},
{'id': 279, 'name': 'Gears of War 2', 'genre': 'Third-person shooter'},
{'id': 280, 'name': 'Gears of War 3', 'genre': 'Third-person shooter'},
{'id': 281, 'name': 'Gears of War 4', 'genre': 'Third-person shooter'},
{'id': 282, 'name': 'Gears of War 5', 'genre': 'Third-person shooter'},
{'id': 283, 'name': 'Halo: Combat Evolved', 'genre': 'First-person shooter'},
{'id': 284, 'name': 'Halo 2', 'genre': 'First-person shooter'},
{'id': 285, 'name': 'Halo 3', 'genre': 'First-person shooter'},
{'id': 286, 'name': 'Halo 3: ODST', 'genre': 'First-person shooter'},
{'id': 287, 'name': 'Halo: Reach', 'genre': 'First-person shooter'},
{'id': 288, 'name': 'Halo 4', 'genre': 'First-person shooter'},
{'id': 289, 'name': 'Halo 5: Guardians', 'genre': 'First-person shooter'},
{'id': 290, 'name': 'Pokémon Red', 'genre': 'Role-playing'},
{'id': 291, 'name': 'Pokémon Blue', 'genre': 'Role-playing'},
{'id': 292, 'name': 'Pokémon Yellow: Special Pikachu Edition', 'genre': 'Role-playing'},
{'id': 293, 'name': 'Pokémon Gold', 'genre': 'Role-playing'},
{'id': 294, 'name': 'Pokémon Silver', 'genre': 'Role-playing'},
{'id': 295, 'name': 'Pokémon Crystal', 'genre': 'Role-playing'},
{'id': 296, 'name': 'Pokémon Ruby', 'genre': 'Role-playing'},
{'id': 297, 'name': 'Pokémon Sapphire', 'genre': 'Role-playing'},
{'id': 298, 'name': 'Pokémon Emerald', 'genre': 'Role-playing'},
{'id': 299, 'name': 'Pokémon FireRed', 'genre': 'Role-playing'},
{'id': 300, 'name': 'Pokémon LeafGreen', 'genre': 'Role-playing'},
{'id': 301, 'name': 'Pokémon Diamond', 'genre': 'Role-playing'},
{'id': 302, 'name': 'Pokémon Pearl', 'genre': 'Role-playing'},
{'id': 303, 'name': 'Pokémon Platinum', 'genre': 'Role-playing'},
{'id': 304, 'name': 'Pokémon HeartGold', 'genre': 'Role-playing'},
{'id': 305, 'name': 'Pokémon SoulSilver', 'genre': 'Role-playing'},
{'id': 306, 'name': 'Pokémon Black', 'genre': 'Role-playing'},
{'id': 307, 'name': 'Pokémon White', 'genre': 'Role-playing'},
{'id': 308, 'name': 'Pokémon Black 2', 'genre': 'Role-playing'},
{'id': 309, 'name': 'Pokémon White 2', 'genre': 'Role-playing'},
{'id': 310, 'name': 'Pokémon X', 'genre': 'Role-playing'},
{'id': 311, 'name': 'Pokémon Y', 'genre': 'Role-playing'},
{'id': 312, 'name': 'Pokémon Omega Ruby', 'genre': 'Role-playing'},
{'id': 313, 'name': 'Pokémon Alpha Sapphire', 'genre': 'Role-playing'},
{'id': 314, 'name': 'Pokémon Sun', 'genre': 'Role-playing'},
{'id': 315, 'name': 'Pokémon Moon', 'genre': 'Role-playing'},
{'id': 316, 'name': 'Pokémon Ultra Sun', 'genre': 'Role-playing'},
{'id': 317, 'name': 'Pokémon Ultra Moon', 'genre': 'Role-playing'},
{'id': 318, 'name': 'Pokémon: Let\'s Go, Pikachu!', 'genre': 'Role-playing'},
{'id': 319, 'name': 'Pokémon: Let\'s Go, Eevee!', 'genre': 'Role-playing'},
{'id': 320, 'name': 'Pokémon Sword', 'genre': 'Role-playing'},
{'id': 321, 'name': 'Pokémon Shield', 'genre': 'Role-playing'},
{'id': 322, 'name': 'Tomb Raider', 'genre': 'Action-Adventure'},
    {'id': 323, 'name': 'Tomb Raider II', 'genre': 'Action-Adventure'},
    {'id': 324, 'name': 'Tomb Raider III', 'genre': 'Action-Adventure'},
    {'id': 325, 'name': 'Tomb Raider: The Last Revelation', 'genre': 'Action-Adventure'},
    {'id': 326, 'name': 'Tomb Raider: Chronicles', 'genre': 'Action-Adventure'},
    {'id': 327, 'name': 'Tomb Raider: The Angel of Darkness', 'genre': 'Action-Adventure'},
    {'id': 328, 'name': 'Tomb Raider: Legend', 'genre': 'Action-Adventure'},
    {'id': 329, 'name': 'Tomb Raider: Anniversary', 'genre': 'Action-Adventure'},
    {'id': 330, 'name': 'Tomb Raider: Underworld', 'genre': 'Action-Adventure'},
    {'id': 331, 'name': 'Tomb Raider (2013)', 'genre': 'Action-Adventure'},
    {'id': 332, 'name': 'Rise of the Tomb Raider', 'genre': 'Action-Adventure'},
    {'id': 333, 'name': 'Shadow of the Tomb Raider', 'genre': 'Action-Adventure'},
    {'id': 334, 'name': 'The Legend of Zelda', 'genre': 'Action-Adventure'},
    {'id': 335, 'name': 'Zelda II: The Adventure of Link', 'genre': 'Action-Adventure'},
    {'id': 336, 'name': 'The Legend of Zelda: A Link to the Past', 'genre': 'Action-Adventure'},
    {'id': 337, 'name': 'The Legend of Zelda: Link\'s Awakening', 'genre': 'Action-Adventure'},
    {'id': 338, 'name': 'The Legend of Zelda: Ocarina of Time', 'genre': 'Action-Adventure'},
    {'id': 339, 'name': 'The Legend of Zelda: Majora\'s Mask', 'genre': 'Action-Adventure'},
    {'id': 340, 'name': 'The Legend of Zelda: Oracle of Ages', 'genre': 'Action-Adventure'},
    {'id': 341, 'name': 'The Legend of Zelda: Oracle of Seasons', 'genre': 'Action-Adventure'},
    {'id': 342, 'name': 'The Legend of Zelda: Four Swords', 'genre': 'Action-Adventure'},
    {'id': 343, 'name': 'The Legend of Zelda: The Wind Waker', 'genre': 'Action-Adventure'},
    {'id': 344, 'name': 'The Legend of Zelda: Four Swords Adventures', 'genre': 'Action-Adventure'},
    {'id': 345, 'name': 'The Legend of Zelda: The Minish Cap', 'genre': 'Action-Adventure'},
    {'id': 346, 'name': 'The Legend of Zelda: Twilight Princess', 'genre': 'Action-Adventure'},
    {'id': 347, 'name': 'The Legend of Zelda: Phantom Hourglass', 'genre': 'Action-Adventure'},
    {'id': 348, 'name': 'The Legend of Zelda: Spirit Tracks', 'genre': 'Action-Adventure'},
    {'id': 349, 'name': 'The Legend of Zelda: Skyward Sword', 'genre': 'Action-Adventure'},
    {'id': 350, 'name': 'The Legend of Zelda: A Link Between Worlds', 'genre': 'Action-Adventure'},
    {'id': 351, 'name': 'The Legend of Zelda: Tri Force Heroes', 'genre': 'Action-Adventure'},
    {'id': 352, 'name': 'The Legend of Zelda: Breath of the Wild', 'genre': 'Action-Adventure'},
    {'id': 353, 'name': 'Hyrule Warriors', 'genre': 'Action'},
    {'id': 354, 'name': 'Hyrule Warriors: Age of Calamity', 'genre': 'Action'},
]


@app.route('/')
def index():
    sorted_games = sorted(games, key=lambda x: x['name'])  # Ordenar todos los juegos por nombre
    return render_template('index.html', games=sorted_games)


@app.route('/add', methods=['GET', 'POST'])
def add_game():
    if request.method == 'POST':
        new_id = len(games) + 1
        new_game = {
            'id': new_id,
            'name': request.form['name'],
            'genre': request.form['genre']
        }
        games.append(new_game)
        return redirect(url_for('index'))
    return render_template('add_game.html')

@app.route('/update/<int:game_id>', methods=['GET', 'POST'])
def update_game(game_id):
    game = next((game for game in games if game['id'] == game_id), None)
    if request.method == 'POST':
        if game:
            game['name'] = request.form['name']
            game['genre'] = request.form['genre']
            return redirect(url_for('index'))
    return render_template('update_game.html', game=game)

@app.route('/delete/<int:game_id>')
def delete_game(game_id):
    global games
    games = [game for game in games if game['id'] != game_id]
    return redirect(url_for('index'))

@app.route('/search', methods=['GET', 'POST'])
def search_game():
    search_results = []
    if request.method == 'POST':
        search_query = request.form['search']
        search_results = [game for game in games if search_query.lower() in game['name'].lower()]
    return render_template('index.html', games=search_results)

if __name__ == '__main__':
    app.run(debug=True)

